Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  # Настройка памяти и процессора (по желанию)
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end

  # Синхронизация папки (чтобы скопировать файл в ВМ)
  config.vm.synced_folder ".", "/vagrant"

  # Скрипт для установки необходимых пакетов
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y python3 python3-pip
    pip3 install psycopg2-binary django
    cp /vagrant/dummy.txt /home/vagrant/dummy.txt
  SHELL
end

